source "https://rubygems.org"

# Jekyll and core plugins
gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"

# Required for Jekyll 4.3+
gem "webrick", "~> 1.8"

# GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Windows-specific gems
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
